#!/bin/bash
# Script to rebase git repository based on upstream
# either provide upstream url or update
# FIXME: URL validation
BRANCH=`git symbolic-ref --short HEAD`
if [ $# -eq 1 ]
then
	git checkout $BRANCH
	if [ $1 != "update" ]
	then
		git remote add upstream $1
	fi
	git fetch upstream
	git rebase upstream/$BRANCH
	git push origin $BRANCH
else
	echo "$0 'upstream URL'"
fi
