#!/bin/bash
PORT=${1:-8000}
shift
if which python3 &> /dev/null; then
	python3 -m http.server $PORT $*
elif which ruby &> /dev/null; then
	ruby -run -ehttpd . -p$PORT $*
elif which php &> /dev/null; then
	php -S 127.0.0.1:$PORT $*
else
	echo "Python/Ruby/PHP not found"
fi