#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform
	for interface in `ifconfig $1 | grep ": flags" | cut -f1 -d":"`; do
	        ip=$(ifconfig $interface | grep "inet " | cut -f2 -d" ")
	        if [ $interface != "lo0" ]; then
	        	ip6=$(ifconfig $interface | grep "inet6" | cut -f2 -d" ")
	        fi
	        if [ ! -z $ip ]; then
	            echo "$interface : $ip"
	        fi
	        if [ ! -z $ip6 ]; then
	            echo "$interface : $ip6"
	        fi	        
	done
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Do something under GNU/Linux platform
    if which ifconfig; then
		for interface in `ifconfig $1 | grep "Link " | cut -f1 -d" "`; do
	        ip=$(ifconfig $interface | tr -s " " | grep "inet" | cut -f2 -d":" | cut -f1 -d" ")
	        if [ $interface != "lo0" ]; then
	        	ip6=$(ifconfig $interface | tr -s " " | grep "inet6" | cut -f2 -d":" | cut -f1 -d" ")
	        fi
	        if [ ! -z $ip ]; then
	            echo "$interface : $ip"
	        fi
	        if [ ! -z $ip6 ]; then
	            echo "$interface : $ip6"
	        fi	        
		done
    else
    	for interface in `ip a | grep mtu | cut -f2 -d":" | tr -s " " | xargs`; do
    		ip=$(ip addr show $interface | grep "inet " | tr -s " " | cut -f3 -d" ")
    		if [ $interface != "lo" ]; then
    				ip6=$(ip addr show $interface | grep "inet6" | tr -s " " | cut -f3 -d" ")
			fi
	        if [ ! -z $ip ]; then
	            echo "$interface : $ip"
	        fi
	        if [ ! -z $ip6 ]; then
	            echo "$interface : $ip6"
	        fi	
    	done
    fi
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under Windows NT platform
    echo "Not implemented for Windows"
fi
